[ftplugin]
_ = '''
'''

html = '''
" Indent settings.
setlocal softtabstop=2
setlocal shiftwidth=2
setlocal smarttab
setlocal expandtab
setlocal shiftround
'''

go = '''
let g:go_def_mode = "gopls"
'''
